spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: phanquangduytvt@gmail.com
    password: vaee dfnf dzvp yiih
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    test-connection: false
    protocol: smtp
  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/donations
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
